[workspace]
members = [
    "picky",
    "picky-server",
    "picky-asn1",
    "picky-asn1-der",
]

[patch.crates-io]
backtrace = { git = "https://github.com/Devolutions/backtrace-rs", branch = "wayk" }
libz-sys = { git = "https://github.com/Devolutions/libz-sys", branch = "wayk" }
rsa = { git = "https://github.com/RustCrypto/RSA" }